name: pages-build-deployment

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pages Replacement
        run: echo "Attempt to replace the locked pages-build-deployment worflow"