name: Production CI

on:
  push:
    branches: [production]
  pull_request:
    branches: [production]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Jest (TS) Testing Procedure
        run: |
          yarn install
          yarn test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo My first Github Action!

      - name: Install npm packages
        run: yarn install

      - name: Transpile Typescript
        run: yarn tsc

      - name: Build IIFE bundle
        run: yarn vite build -c vite.iife.config.js

      - name: Build module bundles
        run: yarn vite build -c vite.mod.config.js

      - name: Build demo site
        run: yarn vite build -c vite.site.config.js

      - name: Build documentation site
        run: yarn typedoc --readme none --excludePrivate --excludeInternal --out docs/typedoc --entryPoints src/Nanosplash.ts src/types.d.ts

      # Persist changes and push
      - name: Commit changes and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Github Actions CI: Build Project for Production"
          git push
